### ISSUE TITLE
Doesn't work with Node-Red 1.0

### ISSUE THREAD

**Issue by oliv3** [sjoerdvanderhoorn/node-red-contrib-tesseract#4]
Hi, I just upgraded Node-Red to 1.0 (1.0.2). Now I get this error message:

```
Error: Cannot find module '/data/node_modules/node-red-contrib-tesseract/tesseract.js-overload/worker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by oliv3** [comment]
In the console, it says it can not find the module 'file-type'

**Comment by timdonovanuk** [comment]
I just get

`abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 100663296, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.") at Error`

**Comment by tedhuang** [comment]
I don't think this is related to Node-RED version.

The problem seems to be that the imported libraries are hard coded to expect certain paths. However if you install your nodes using the npm `--global-style` flag the library dependencies would be installed under a `node_modules` folder in the node directory itself which causes the error.

This line

`const workerUtils = require('../../tesseract.js/src/common/worker.js')`

would be

`const workerUtils = require('../node_modules/tesseract.js/src/common/worker.js')`

https://github.com/sjoerdvanderhoorn/node-red-contrib-tesseract/blob/6b429db0feb65745113deef1b31366db81ea19ae/tesseract.js-overload/worker.js#L1

This is also relevant in `tesseract.js-overload/lang.js:6`

**Comment by timdonovanuk** [comment]
I think for me I was trying to OCR a super large image. It's been working great for me after that on the latest versions!
